import DetailsToggle from "./DetailsToggle";
import Logo from "./Logo";

function WorkExperience() {
  return (
    <div>
      <h2 className="text-2xl text-highlight">Work Experience</h2>
      <div className="mt-8 flex flex-col gap-6">
        <div className="flex gap-4 md:gap-6">
          <Logo src="/images/accenture_logo.png" alt="Accenture logo" />
          <div>
            <p className="text-highlight">Accenture</p>
            <p>Software Engineer (Frontend)</p>
            <p>Kolkata, West Bengal, India</p>
            <p>Mar 2022 - Aug 2023</p>
            <DetailsToggle>
              <ul className="mt-2 flex flex-col gap-2 list-disc ml-4">
                <li>
                  Worked for 4 major feature releases and delivered crucial
                  application functionalities like Advanced Search, Session
                  Management, Scratchpad etc., and fixed 30+ technical bugs and
                  styling issues across the entire application.
                </li>
                <li>
                  Achieved a 17% reduction in bundle sizes and improved
                  performance score from 62 to 71 in Chrome Lighthouse by
                  migrating application components from Material-UI and
                  KendoReact to Radix-UI and Tailwind CSS, while maintaining the
                  same look and feel.
                </li>
                <li>
                  Enhanced the usability, performance, and customizability of 4
                  different components of the in-house component library used by
                  5 different applications, by leveraging modern browser
                  features, removing unnecessary side effects, and utilizing
                  caching where applicable.
                </li>
              </ul>
            </DetailsToggle>
          </div>
        </div>

        <div className="flex gap-4 md:gap-6">
          <Logo src="/images/cognizant_logo.jpeg" alt="Cognizant logo" />
          <div>
            <p className="text-highlight">Cognizant</p>
            <p>Software Engineer</p>
            <p>Kolkata, West Bengal, India</p>
            <p>Jul 2019 - Mar 2022</p>
            <DetailsToggle>
              <ul className="mt-2 flex flex-col gap-2 list-disc ml-4">
                <li>
                  Developed a real-time data integration system between
                  Salesforce and Redtail CRMs using Salesforce triggers, batch
                  jobs, MuleSoft AnyPoint Platform and Azure message queues,
                  that significantly eased the workflows of financial advisors
                  and facilitated the onboarding of more than 60 new advisors
                  within 9 months.
                </li>
                <li>
                  Designed 7 different HubSpot CRM workflows that reduced
                  friction in driving email marketing campaigns, empowering more
                  than 20 marketing consultants.
                </li>
                <li>
                  Implemented an in-house JavaScript network logger library with
                  support for different log levels and schema validation and
                  integrated it with Elasticsearch, that was quickly adopted for
                  use by 3+ applications in the project.
                </li>
                <li>
                  Created 5+ APIs to provide applications with access to
                  demographic data and created a Windows service using C# and
                  .NET framework to periodically archive local log files
                  generated by applications.
                </li>
                <li>
                  Built the user interface of a marketing automation application
                  using React and an analytics dashboard in Kibana that
                  streamlined the process of marketing data collection and
                  monitoring for financial advisors.
                </li>
              </ul>
            </DetailsToggle>
          </div>
        </div>
      </div>
    </div>
  );
}

export default WorkExperience;
